In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving bengaluru_house_prices.csv to bengaluru_house_prices (1).csv
Saving gurgaon_10k.csv to gurgaon_10k (1).csv
Saving hyderabad.csv to hyderabad (1).csv
Saving kolkata.csv to kolkata (1).csv
Saving mumbai.csv to mumbai (1).csv

In [ ]:
import pandas as pd
import numpy as np

df2 = pd.read_csv("gurgaon_10k.csv", low_memory=False)
df3 = pd.read_csv("hyderabad.csv", low_memory=False)
df4 = pd.read_csv("mumbai.csv", low_memory=False)
df5 = pd.read_csv("kolkata.csv", low_memory=False)

In [ ]:
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df4.columns)
print(df5.columns)

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')
Index(['PROP_ID', 'PHOTO_URL', 'MEDIUM_PHOTO_URL', 'PREFERENCE', 'DESCRIPTION',
       'PROPERTY_TYPE', 'CITY', 'LOCALITY', 'TRANSACT_TYPE', 'OWNTYPE',
       'BEDROOM_NUM', 'BATHROOM_NUM', 'BALCONY_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'FLOOR_NUM', 'TOTAL_FLOOR', 'FEATURES',
       'REGISTER_DATE', 'PROP_NAME', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT',
       'LISTING', 'BUILDING_ID', 'CARPET_SQFT', 'SUPERBUILTUP_SQFT',
       'BROKERAGE', 'MAP_DETAILS', 'FSL_Data', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'FORMATTED', 'AMENITIES', 'TOP_USPS', 'PD_URL',
       'EXPIRY_DATE', 'GROUP_NAME', 'AREA', 'PRICE', 'PROP_HEADING',
       'PROP_DETAILS_URL', 'CLASS_HEADING', 'CLASS_LABEL', 'SECONDARY_TAGS',
       'PROPERTY_IMAGES', 'THUMBNAIL_IMAGES', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'CONTACT_NAME', 'CONTACT_COMPANY_NAME',
       'DEALER_PHOTO_URL', 'SOCIETY_NAME', 'BUILDING_NAME', 'CITY_ID',
       'LOCALITY_WO_CITY', 'profile', 'xid', 'metadata', 'location',
       'BUILTUP_SQFT', 'SUPER_SQFT', 'COMMON_FURNISHING_ATTRIBUTES',
       'QUALITY_SCORE', 'FURNISHING_ATTRIBUTES'],
      dtype='object')
Index(['SPID', 'PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'REGISTER_DATE',
       'POSTING_DATE', 'UPDATE_DATE', 'CLASS', 'RES_COM', 'PROP_NAME',
       'PROPERTY_NUMBER', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT', 'PROJ_ID',
       'BUILDING_ID', 'VERIFIED', 'MAP_DETAILS', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'AMENITIES', 'ALT_TAG', 'PRODUCT_TYPE', 'TOP_USPS',
       'EXPIRY_DATE', 'PROPERTY_TYPE__U', 'AREA', 'SECONDARY_AREA', 'PRICE',
       'PROP_HEADING', 'VALUE_LABEL', 'CLASS_HEADING', 'CLASS_LABEL',
       'REGISTER_DATE__U', 'REGISTERED_DAYS', 'PRIMARY_TAGS', 'SECONDARY_TAGS',
       'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME',
       'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM'],
      dtype='object')
Index(['SPID', 'PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'REGISTER_DATE',
       'POSTING_DATE', 'UPDATE_DATE', 'CLASS', 'RES_COM', 'PROP_NAME',
       'PROPERTY_NUMBER', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT', 'PROJ_ID',
       'BUILDING_ID', 'VERIFIED', 'MAP_DETAILS', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'AMENITIES', 'ALT_TAG', 'PRODUCT_TYPE', 'TOP_USPS',
       'EXPIRY_DATE', 'PROPERTY_TYPE__U', 'AREA', 'SECONDARY_AREA', 'PRICE',
       'PROP_HEADING', 'VALUE_LABEL', 'CLASS_HEADING', 'CLASS_LABEL',
       'REGISTER_DATE__U', 'REGISTERED_DAYS', 'PRIMARY_TAGS', 'SECONDARY_TAGS',
       'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME',
       'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM'],
      dtype='object')
Index(['PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'PROP_NAME',
       'PRICE_SQFT', 'MAP_DETAILS', 'AMENITIES', 'AREA', 'PRICE',
       'PROP_HEADING', 'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME', 'BUILDING_NAME',
       'location', 'BALCONY_NUM', 'FLOOR_NUM', 'CARPET_SQFT',
       'SUPERBUILTUP_SQFT', 'BUILTUP_SQFT', 'SUPER_AREA', 'SUPERAREA_UNIT',
       'SUPER_SQFT'],
      dtype='object')

In [ ]:
print("Before creating price:", 'PRICE' in gurgaon.columns)
gurgaon['price'] = gurgaon['PRICE']
print("After creating price:", 'price' in gurgaon.columns)

Before creating price: False

KeyError: 'PRICE'

In [ ]:
# STEP 1: always work on copy
gurgaon = df2.copy()

# STEP 2: create target column FIRST
gurgaon['price'] = gurgaon['PRICE']

# STEP 3: verify immediately
assert 'price' in gurgaon.columns, "price creation failed"

In [ ]:
common_columns = [
'city',
'locality',
'property_type',
'bhk',
'bathrooms',
'balconies',
'area_sqft',
'property_age',
'floor_number',
'total_floor',
'furnished_status',
'parking',
'availability',
'latitude',
'longitude',
]

In [ ]:
blr = df1.copy()

blr['city'] = 'Bangalore'
blr['locality'] = blr['location']
blr['property_type'] = blr['area_type']
blr['bhk'] = blr['size'].str.extract('(\d+)').astype(float)
blr['bathrooms'] = blr['bath']
blr['balconies'] = blr['balcony']
blr['area_sqft'] = blr['total_sqft']
blr['property_age'] = np.nan
blr['floor_number'] = np.nan
blr['total_floor'] = np.nan
blr['furnished_status'] = np.nan
blr['parking'] = np.nan
blr['availability'] = np.nan
blr['latitude'] = np.nan
blr['longitude'] = np.nan

blr = blr[common_columns + ['price']]

<>:6: SyntaxWarning: invalid escape sequence '\d'
<>:6: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_1458/1663920814.py:6: SyntaxWarning: invalid escape sequence '\d'
  blr['bhk'] = blr['size'].str.extract('(\d+)').astype(float)

In [ ]:
print('price' in gurgaon.columns)  # must be True

True

In [ ]:
valid_cols = [c for c in common_columns if c in gurgaon.columns]
gurgaon = gurgaon[valid_cols + ['price']]

In [ ]:
gurgaon = df2.copy()

gurgaon['city'] = gurgaon['CITY']
gurgaon['locality'] = gurgaon['LOCALITY']
gurgaon['property_type'] = gurgaon['PROPERTY_TYPE']
gurgaon['bhk'] = gurgaon['BEDROOM_NUM']
gurgaon['bathrooms'] = gurgaon['BATHROOM_NUM']
gurgaon['balconies'] = gurgaon['BALCONY_NUM']
gurgaon['property_age'] = gurgaon['AGE']
gurgaon['floor_number'] = gurgaon['FLOOR_NUM']
gurgaon['total_floor'] = gurgaon['TOTAL_FLOOR']
gurgaon['furnished_status'] = gurgaon['FURNISH']
gurgaon['area_sqft'] = gurgaon['AREA']
gurgaon['parking'] = np.nan
gurgaon['availability'] = np.nan
gurgaon['latitude'] = np.nan
gurgaon['longitude'] = np.nan

gurgaon['price'] = gurgaon['PRICE']

gurgaon = gurgaon[common_columns + ['price']]

In [ ]:
print(gurgaon.columns.tolist())

['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies', 'area_sqft', 'property_age', 'floor_number', 'total_floor', 'furnished_status', 'parking', 'availability', 'latitude', 'longitude', 'price']

In [ ]:
print(df3.columns)

Index(['SPID', 'PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'REGISTER_DATE',
       'POSTING_DATE', 'UPDATE_DATE', 'CLASS', 'RES_COM', 'PROP_NAME',
       'PROPERTY_NUMBER', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT', 'PROJ_ID',
       'BUILDING_ID', 'VERIFIED', 'MAP_DETAILS', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'AMENITIES', 'ALT_TAG', 'PRODUCT_TYPE', 'TOP_USPS',
       'EXPIRY_DATE', 'PROPERTY_TYPE__U', 'AREA', 'SECONDARY_AREA', 'PRICE',
       'PROP_HEADING', 'VALUE_LABEL', 'CLASS_HEADING', 'CLASS_LABEL',
       'REGISTER_DATE__U', 'REGISTERED_DAYS', 'PRIMARY_TAGS', 'SECONDARY_TAGS',
       'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME',
       'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM'],
      dtype='object')

In [ ]:
hyd = df3.copy()

hyd['city'] = hyd['CITY']
hyd['locality'] = hyd['location']
hyd['property_type'] = hyd['PROPERTY_TYPE']
hyd['bhk'] = hyd['BEDROOM_NUM']
hyd['bathrooms'] = np.nan
hyd['balconies'] = hyd['BALCONY_NUM']
hyd['property_age'] = hyd['AGE']
hyd['floor_number'] = hyd['FLOOR_NUM']
hyd['total_floor'] = hyd['TOTAL_FLOOR']
hyd['furnished_status'] = hyd['FURNISH']
hyd['area_sqft'] = hyd['MAX_AREA_SQFT']
hyd['parking'] = np.nan
hyd['availability'] = np.nan
hyd['latitude'] = np.nan
hyd['longitude'] = np.nan

hyd['price'] = hyd['PRICE']

hyd = hyd[common_columns + ['price']]

In [ ]:
print(df4['CITY'].unique())
print(df5['CITY'].unique())

['Mumbai Beyond Thane' 'Navi Mumbai' 'Thane' 'Mumbai Harbour'
 'South Mumbai' 'Central Mumbai suburbs' 'Mumbai South West'
 'Mumbai Andheri-Dahisar' 'Mira Road And Beyond']
['Kolkata South' 'Kolkata North' 'Kolkata Central' 'Kolkata East'
 'Kolkata West']

In [ ]:
print(df5.columns)

Index(['PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'PROP_NAME',
       'PRICE_SQFT', 'MAP_DETAILS', 'AMENITIES', 'AREA', 'PRICE',
       'PROP_HEADING', 'SECONDARY_TAGS', 'TOTAL_LANDMARK_COUNT',
       'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME', 'BUILDING_NAME',
       'location', 'BALCONY_NUM', 'FLOOR_NUM', 'CARPET_SQFT',
       'SUPERBUILTUP_SQFT', 'BUILTUP_SQFT', 'SUPER_AREA', 'SUPERAREA_UNIT',
       'SUPER_SQFT'],
      dtype='object')

In [ ]:
kol = df5.copy()

kol['city'] = kol['CITY']
kol['locality'] = kol['location']
kol['property_type'] = kol['PROPERTY_TYPE']
kol['bhk'] = kol['BEDROOM_NUM']
kol['bathrooms'] = np.nan
kol['balconies'] = kol['BALCONY_NUM']
kol['property_age'] = kol['AGE']
kol['floor_number'] = kol['FLOOR_NUM']
kol['total_floor'] = kol['TOTAL_FLOOR']
kol['furnished_status'] = kol['FURNISH']
kol['parking'] = np.nan
kol['availability'] = np.nan
kol['latitude'] = np.nan
kol['longitude'] = np.nan

# Area
kol['area_sqft'] = kol['AREA']

# Price
kol['price'] = kol['PRICE']
kol = kol[common_columns + ['price']]

In [ ]:
print(df4.columns)

Index(['SPID', 'PROP_ID', 'PREFERENCE', 'DESCRIPTION', 'PROPERTY_TYPE', 'CITY',
       'TRANSACT_TYPE', 'OWNTYPE', 'BEDROOM_NUM', 'PRICE_PER_UNIT_AREA',
       'FURNISH', 'FACING', 'AGE', 'TOTAL_FLOOR', 'FEATURES', 'REGISTER_DATE',
       'POSTING_DATE', 'UPDATE_DATE', 'CLASS', 'RES_COM', 'PROP_NAME',
       'PROPERTY_NUMBER', 'MIN_PRICE', 'MAX_PRICE', 'PRICE_SQFT', 'PROJ_ID',
       'BUILDING_ID', 'VERIFIED', 'MAP_DETAILS', 'MIN_AREA_SQFT',
       'MAX_AREA_SQFT', 'AMENITIES', 'ALT_TAG', 'PRODUCT_TYPE', 'TOP_USPS',
       'EXPIRY_DATE', 'PROPERTY_TYPE__U', 'AREA', 'SECONDARY_AREA', 'PRICE',
       'PROP_HEADING', 'VALUE_LABEL', 'CLASS_HEADING', 'CLASS_LABEL',
       'REGISTER_DATE__U', 'REGISTERED_DAYS', 'PRIMARY_TAGS', 'SECONDARY_TAGS',
       'TOTAL_LANDMARK_COUNT', 'FORMATTED_LANDMARK_DETAILS', 'SOCIETY_NAME',
       'BUILDING_NAME', 'location', 'BALCONY_NUM', 'FLOOR_NUM'],
      dtype='object')

In [ ]:
mum = df4.copy()

mum['city'] = mum['CITY']
mum['locality'] = mum['location']
mum['property_type'] = mum['PROPERTY_TYPE']
mum['bhk'] = mum['BEDROOM_NUM']
mum['bathrooms'] = np.nan
mum['balconies'] = mum['BALCONY_NUM']
mum['property_age'] = mum['AGE']
mum['floor_number'] = mum['FLOOR_NUM']
mum['total_floor'] = mum['TOTAL_FLOOR']
mum['furnished_status'] = mum['FURNISH']
mum['parking'] = np.nan
mum['availability'] = np.nan
mum['latitude'] = np.nan
mum['longitude'] = np.nan
mum['area_sqft'] = mum['MAX_AREA_SQFT']

mum['price'] = mum['PRICE']
mum = mum[common_columns + ['price']]

In [ ]:
for df in [blr,gurgaon,hyd,kol,mum]:
    print(df.columns)

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')

In [ ]:
all_df = pd.concat([blr, gurgaon, hyd, kol, mum], ignore_index=True)

print(all_df.shape)
print(all_df['price'].isnull().sum())

(51822, 16)
0

In [ ]:
all_df.to_csv("property_master.csv", index=False)

In [ ]:
all_df.columns

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')

In [ ]:
all_df.shape

(51822, 16)

In [ ]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51822 entries, 0 to 51821
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   city              51822 non-null  object
 1   locality          51821 non-null  object
 2   property_type     51822 non-null  object
 3   bhk               48252 non-null  float64
 4   bathrooms         23951 non-null  float64
 5   balconies         41216 non-null  float64
 6   area_sqft         51822 non-null  object
 7   property_age      38502 non-null  float64
 8   floor_number      31981 non-null  object
 9   total_floor       37850 non-null  float64
 10  furnished_status  38502 non-null  float64
 11  parking           0 non-null      float64
 12  availability      0 non-null      float64
 13  latitude          0 non-null      float64
 14  longitude         0 non-null      float64
 15  price             51822 non-null  object
dtypes: float64(10), object(6)
memory usage: 6.3+ MB

In [ ]:

all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                   0
dtype: int64

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                   0
dtype: int64

In [ ]:
print(all_df.columns)

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                   0
dtype: int64

In [ ]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51822 entries, 0 to 51821
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   city              51822 non-null  object
 1   locality          51821 non-null  object
 2   property_type     51822 non-null  object
 3   bhk               48252 non-null  float64
 4   bathrooms         23951 non-null  float64
 5   balconies         41216 non-null  float64
 6   area_sqft         51822 non-null  object
 7   property_age      38502 non-null  float64
 8   floor_number      31981 non-null  object
 9   total_floor       37850 non-null  float64
 10  furnished_status  38502 non-null  float64
 11  parking           0 non-null      float64
 12  availability      0 non-null      float64
 13  latitude          0 non-null      float64
 14  longitude         0 non-null      float64
 15  price             51822 non-null  object
dtypes: float64(10), object(6)
memory usage: 6.3+ MB

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                   0
dtype: int64

In [ ]:
all_df.loc[
    pd.to_numeric(all_df['price'], errors='coerce').isna(),
    'price'
].value_counts().head(20)

price
Price on Request    394
2 Cr                285
1.5 Cr              279
1.1 Cr              272
1.3 Cr              272
1.6 Cr              259
1.2 Cr              246
2.5 Cr              242
1.4 Cr              229
75 L                228
3.5 Cr              225
1.75 Cr             224
1.35 Cr             223
2.1 Cr              220
1.7 Cr              219
1.25 Cr             215
1.8 Cr              215
1.9 Cr              215
1.65 Cr             213
65 L                213
Name: count, dtype: int64

In [ ]:
all_df['price'].astype(str).value_counts().head(50)

price
Price on Request    394
75.0                310
65.0                302
2 Cr                285
1.5 Cr              279
55.0                275
1.3 Cr              272
1.1 Cr              272
60.0                270
1.6 Cr              259
1.2 Cr              246
2.5 Cr              242
45.0                240
50.0                235
1.4 Cr              229
75 L                228
3.5 Cr              225
1.75 Cr             224
1.35 Cr             223
2.1 Cr              220
1.7 Cr              219
1.9 Cr              215
1.8 Cr              215
1.25 Cr             215
1.65 Cr             213
65 L                213
1.55 Cr             213
1.15 Cr             209
70.0                208
50 L                204
90.0                203
85 L                203
85.0                201
5 Cr                200
2.25 Cr             198
45 L                195
90 L                194
3 Cr                194
1 Cr                193
2.3 Cr              192
1.45 Cr             186
110.0               185
80.0                185
1.05 Cr             181
150.0               180
2.2 Cr              178
100.0               177
80 L                177
95.0                177
60 L                176
Name: count, dtype: int64

In [ ]:
all_df[all_df['price'].astype(str).str.contains('-', na=False)]['price'].head(20)

14292       5.2  - 6.3 Cr
14397     5.39  - 6.33 Cr
14398      3.8  - 4.26 Cr
14941      1.3  - 1.31 Cr
14943      1.3  - 1.31 Cr
24025      69.3  - 83.7 L
24027     2.02  - 2.02 Cr
24028     2.42  - 2.87 Cr
24029     7.59  - 9.25 Cr
24030     1.25  - 1.48 Cr
24031      80.09 L - 3 Cr
24032      1.8  - 2.43 Cr
24034     2.32  - 2.32 Cr
24035     1.35  - 1.42 Cr
24037       2.5  - 2.5 Cr
24038            0 - 1 Cr
24039    91.97  - 93.23 L
24042     1.28  - 19.2 Cr
24043    85.88  - 93.75 L
24044     1.08  - 1.28 Cr
Name: price, dtype: object

In [ ]:
import pandas as pd
import numpy as np

def convert_price(price):
    if pd.isna(price):
        return np.nan

    price = str(price).replace(',', '').strip()

    if price.lower() == 'price on request':
        return np.nan

    try:
        # Range values
        if '-' in price:
            if 'Cr' in price:
                nums = price.replace('Cr', '').split('-')
                nums = [float(x.strip()) for x in nums]
                return np.mean(nums) * 1e7

            elif 'L' in price:
                nums = price.replace('L', '').split('-')
                nums = [float(x.strip()) for x in nums]
                return np.mean(nums) * 1e5

        # Single values
        if 'Cr' in price:
            return float(price.replace('Cr', '').strip()) * 1e7

        if 'L' in price:
            return float(price.replace('L', '').strip()) * 1e5

        return float(price)

    except:
        return np.nan

all_df['price'] = all_df['price'].apply(convert_price)

In [ ]:
bad_values = all_df.loc[
    all_df['price'].astype(str).apply(lambda x: convert_price(x) is np.nan),
    'price'
].unique()

print(bad_values[:50])

[]

In [ ]:
bad_prices = all_df.loc[all_df['price'].isna(), 'price']
print(bad_prices.head(50))

13516   NaN
14133   NaN
15294   NaN
15967   NaN
16003   NaN
16021   NaN
17750   NaN
17875   NaN
18182   NaN
18183   NaN
18184   NaN
18185   NaN
18712   NaN
19252   NaN
19253   NaN
19259   NaN
19260   NaN
19261   NaN
19484   NaN
21881   NaN
22901   NaN
23078   NaN
24026   NaN
24031   NaN
24041   NaN
24045   NaN
24049   NaN
24050   NaN
24051   NaN
24052   NaN
24054   NaN
24055   NaN
24061   NaN
24062   NaN
24063   NaN
24064   NaN
24068   NaN
24070   NaN
24076   NaN
24078   NaN
24079   NaN
24084   NaN
24088   NaN
24094   NaN
24107   NaN
24108   NaN
24110   NaN
24111   NaN
24113   NaN
24116   NaN
Name: price, dtype: float64

In [ ]:
print(all_df['price'].isna().sum())

2707

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                2707
dtype: int64

In [ ]:
all_df = all_df.dropna(subset=['price'])

In [ ]:
print(all_df['price'].isna().sum())

0

In [ ]:
for x in all_df['price'].astype(str).unique():
    try:
        convert_price(x)
    except:
        print(x)

In [ ]:
all_df.loc[
    pd.to_numeric(all_df['price'], errors='coerce').isna(),
    'price'
].value_counts().head(20)

Series([], Name: count, dtype: int64)

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3511
bathrooms           25186
balconies            9822
area_sqft               0
property_age        13320
floor_number        19498
total_floor         13941
furnished_status    13320
parking             49115
availability        49115
latitude            49115
longitude           49115
price                   0
dtype: int64

In [ ]:
all_df['price'].dtype

dtype('float64')

In [ ]:
all_df.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3511
bathrooms           25186
balconies            9822
area_sqft               0
property_age        13320
floor_number        19498
total_floor         13941
furnished_status    13320
parking             49115
availability        49115
latitude            49115
longitude           49115
price                   0
dtype: int64

In [ ]:
all_df['area_sqft'].sample(20)

27661           154.683495
18035          4950 sq.ft.
27136             167.2254
49684             78.96755
8976                  1180
26740           142.606105
31637            142.14159
270                    913
46223             76.18046
29240            2090.3175
50709             69.67725
29462           181.811171
32831            205.31563
29352            37.625715
28491           165.831855
33533    1146-1360  sq.ft.
30315           230.863955
51214             111.4836
14511          1805 sq.ft.
7711                  1200
Name: area_sqft, dtype: object

In [ ]:
def convert_area(x):
    try:
        if isinstance(x, str):
            if '-' in x:
                nums = x.split('-')
                return (float(nums[0]) + float(nums[1]))/2
            else:
                return float(x)
        return x
    except:
        return np.nan

all_df['area_sqft'] = (
    all_df['area_sqft']
    .apply(convert_area)
)

/tmp/ipykernel_1458/2735359224.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df['area_sqft'] = (

In [ ]:
all_df.drop(
    columns=[
        'parking',
        'availability',
        'latitude',
        'longitude'
    ],
    inplace=True
)

/tmp/ipykernel_1458/3120666441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df.drop(

In [ ]:

all_df.to_csv(
    "property_master.csv",
    index=False
)

In [ ]:
economic_dataset = pd.read_csv("economic_dataset.csv")

In [ ]:
economic_dataset.columns

Index(['state', 'population_score', 'literacy_score', 'healthcare_score',
       'crime_index', 'road_score', 'infrastructure_score', 'risk_score'],
      dtype='object')

In [ ]:
city_to_state = {
    'Bangalore':'KARNATAKA',
    'Bengaluru':'KARNATAKA',
    'Hyderabad':'TELANGANA',
    'Mumbai':'MAHARASHTRA',
    'Kolkata':'WEST BENGAL',
    'Gurgaon':'HARYANA'
}

In [ ]:

all_df['city'] = (
    all_df['city']
    .astype(str)
    .str.strip()
)

/tmp/ipykernel_1458/1870477374.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df['city'] = (

In [ ]:
all_df['state'] = all_df['city'].map(city_to_state)

/tmp/ipykernel_1458/1397203119.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df['state'] = all_df['city'].map(city_to_state)

In [ ]:
all_df[['city','state']].head()

        city      state
0  Bangalore  KARNATAKA
1  Bangalore  KARNATAKA
2  Bangalore  KARNATAKA
3  Bangalore  KARNATAKA
4  Bangalore  KARNATAKA

In [ ]:
all_df['state'] = (
    all_df['state']
    .str.upper()
    .str.strip()
)

economic_dataset['state'] = (
    economic_dataset['state']
    .str.upper()
    .str.strip()
)

/tmp/ipykernel_1458/1881151664.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_df['state'] = (

In [ ]:
print(all_df.columns)
print(economic_dataset.columns)

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'price', 'state'],
      dtype='object')
Index(['state', 'population_score', 'literacy_score', 'healthcare_score',
       'crime_index', 'road_score', 'infrastructure_score', 'risk_score'],
      dtype='object')

In [ ]:
print(master_dataset.columns[master_dataset.columns.str.contains('price')])

Index(['price'], dtype='object')

In [ ]:
master_dataset = all_df.merge(
    economic_dataset,
    on='state',
    how='left'
)

In [ ]:
master_dataset.shape

(49115, 20)

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3511
bathrooms               25186
balconies                9822
area_sqft               18955
property_age            13320
floor_number            19498
total_floor             13941
furnished_status        13320
price                       0
state                   16618
population_score        25113
literacy_score          25113
healthcare_score        25113
crime_index             25113
road_score              25113
infrastructure_score    25113
risk_score              25113
dtype: int64

In [ ]:
master_dataset.columns

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'price', 'state', 'population_score',
       'literacy_score', 'healthcare_score', 'crime_index', 'road_score',
       'infrastructure_score', 'risk_score'],
      dtype='object')

In [ ]:
master_dataset = master_dataset.loc[:,~master_dataset.columns.duplicated()]

In [ ]:
master_dataset['price'].isnull().sum()

np.int64(0)

In [ ]:
master_dataset['city'].value_counts()

city
Bangalore                 13320
Gurgaon                   10682
Hyderabad                  8495
Kolkata South              3500
Kolkata East               2799
Navi Mumbai                1997
Kolkata North              1651
Central Mumbai suburbs     1469
Thane                      1310
Mumbai Andheri-Dahisar      970
Secunderabad                703
South Mumbai                585
Mumbai Beyond Thane         455
Mira Road And Beyond        331
Mumbai Harbour              315
Mumbai South West           256
Kolkata West                219
Kolkata Central              58
Name: count, dtype: int64

In [ ]:
master_dataset[master_dataset['state'].isna()]['city'].unique()

array(['Secunderabad', 'Kolkata South', 'Kolkata North', 'Kolkata East',
       'Kolkata West', 'Kolkata Central', 'Mumbai Beyond Thane',
       'Navi Mumbai', 'Thane', 'Mumbai Andheri-Dahisar',
       'Central Mumbai suburbs', 'Mumbai South West', 'South Mumbai',
       'Mumbai Harbour', 'Mira Road And Beyond'], dtype=object)

In [ ]:
city_to_state = {
'Bangalore':'KARNATAKA',
'Bengaluru':'KARNATAKA',

'Hyderabad':'TELANGANA',
'HYDERABAD':'TELANGANA',

'Mumbai':'MAHARASHTRA',
'MUMBAI':'MAHARASHTRA',

'Kolkata':'WEST BENGAL',
'KOLKATA':'WEST BENGAL',

'Gurgaon':'HARYANA',
'GURGAON':'HARYANA'
}

In [ ]:
master_dataset['state'] = (
    master_dataset['city']
    .astype(str)
    .str.strip()
    .map(city_to_state)
)

In [ ]:
master_dataset = master_dataset.drop(
columns=[
'population_score',
'literacy_score',
'healthcare_score',
'crime_index',
'road_score',
'infrastructure_score',
'risk_score'
],
errors='ignore'
)

In [ ]:
master_dataset = master_dataset.merge(
economic_dataset,
on='state',
how='left'
)

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3511
bathrooms               25186
balconies                9822
area_sqft               18955
property_age            13320
floor_number            19498
total_floor             13941
furnished_status        13320
price                       0
state                   16618
population_score        25113
literacy_score          25113
healthcare_score        25113
crime_index             25113
road_score              25113
infrastructure_score    25113
risk_score              25113
dtype: int64

In [ ]:
master_dataset[master_dataset['state'].isnull()]['city'].value_counts()

city
Kolkata South             3500
Kolkata East              2799
Navi Mumbai               1997
Kolkata North             1651
Central Mumbai suburbs    1469
Thane                     1310
Mumbai Andheri-Dahisar     970
Secunderabad               703
South Mumbai               585
Mumbai Beyond Thane        455
Mira Road And Beyond       331
Mumbai Harbour             315
Mumbai South West          256
Kolkata West               219
Kolkata Central             58
Name: count, dtype: int64

In [ ]:
city_to_state = {

    # Bangalore
    'BANGALORE':'KARNATAKA',
    'BENGALURU':'KARNATAKA',

    # Hyderabad
    'HYDERABAD':'TELANGANA',
    'SECUNDERABAD':'TELANGANA',

    # Mumbai Region
    'MUMBAI':'MAHARASHTRA',
    'NAVI MUMBAI':'MAHARASHTRA',
    'CENTRAL MUMBAI SUBURBS':'MAHARASHTRA',
    'MUMBAI ANDHERI-DAHISAR':'MAHARASHTRA',
    'THANE':'MAHARASHTRA',
    'SOUTH MUMBAI':'MAHARASHTRA',
    'MUMBAI BEYOND THANE':'MAHARASHTRA',
    'MUMBAI HARBOUR':'MAHARASHTRA',
    'MUMBAI SOUTH WEST':'MAHARASHTRA',
    'MIRA ROAD AND BEYOND':'MAHARASHTRA',

    # Kolkata Region
    'KOLKATA':'WEST BENGAL',
    'KOLKATA NORTH':'WEST BENGAL',
    'KOLKATA SOUTH':'WEST BENGAL',
    'KOLKATA EAST':'WEST BENGAL',
    'KOLKATA WEST':'WEST BENGAL',
    'KOLKATA CENTRAL':'WEST BENGAL',

    # Gurgaon
    'GURGAON':'HARYANA'
}

In [ ]:
master_dataset['city'] = (
    master_dataset['city']
    .astype(str)
    .str.upper()
    .str.strip()
)

In [ ]:
master_dataset['state'] = master_dataset['city'].map(city_to_state)

In [ ]:
master_dataset[master_dataset['state'].isnull()]['city'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
master_dataset['state'].isnull().sum()

np.int64(0)

In [ ]:
master_dataset = master_dataset.drop(
columns=[
'population_score',
'literacy_score',
'healthcare_score',
'crime_index',
'road_score',
'infrastructure_score',
'risk_score'
],
errors='ignore'
)

In [ ]:
master_dataset = master_dataset.merge(
    economic_dataset,
    on='state',
    how='left'
)

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3511
bathrooms               25186
balconies                9822
area_sqft               18955
property_age            13320
floor_number            19498
total_floor             13941
furnished_status        13320
price                       0
state                       0
population_score         9198
literacy_score           9198
healthcare_score         9198
crime_index              9198
road_score               9198
infrastructure_score     9198
risk_score               9198
dtype: int64

In [ ]:
master_dataset[
    master_dataset['population_score'].isnull()
]['state'].value_counts()

state
TELANGANA    9198
Name: count, dtype: int64

In [ ]:
economic_dataset['state'].unique()

array(['A & N ISLANDS', 'ALL INDIA', 'ALL INDIA TOTAL',
       'ANDAMAN & NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ANDHRA PRADESH1',
       'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH',
       'CHHATTISGARH', 'D & N HAVELI', 'DADRA & NAGAR HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'DELHI2', 'GOA', 'GUJARAT', 'HARYANA',
       'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JAMMU & KASHMIR+',
       'JHARKHAND', 'KARNATAKA', 'KARNATAKA1', 'KERALA', 'KERALA2',
       'LAKSHADWEEP', 'MADHYA PRADESH', 'MADHYA PRADESH1', 'MAHARASHTRA',
       'MANIPUR', 'MANIPUR1', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'NCT OF DELHI', 'ODISHA', 'PUDUCHERRY', 'PUDUCHERRY2', 'PUNJAB',
       'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH',
       'UTTAR PRADESH3', 'UTTARAKHAND', 'WEST BENGAL', 'WEST BENGAL1'],
      dtype=object)

In [ ]:
master_dataset['state'].unique()

array(['KARNATAKA', 'HARYANA', 'TELANGANA', 'WEST BENGAL', 'MAHARASHTRA'],
      dtype=object)

In [ ]:
set(master_dataset['state'].unique()) - set(economic_dataset['state'].unique())

{'TELANGANA'}

In [ ]:
economic_dataset['state'].unique()

array(['A & N ISLANDS', 'ALL INDIA', 'ALL INDIA TOTAL',
       'ANDAMAN & NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ANDHRA PRADESH1',
       'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH',
       'CHHATTISGARH', 'D & N HAVELI', 'DADRA & NAGAR HAVELI',
       'DAMAN & DIU', 'DELHI UT', 'DELHI2', 'GOA', 'GUJARAT', 'HARYANA',
       'HIMACHAL PRADESH', 'JAMMU & KASHMIR', 'JAMMU & KASHMIR+',
       'JHARKHAND', 'KARNATAKA', 'KARNATAKA1', 'KERALA', 'KERALA2',
       'LAKSHADWEEP', 'MADHYA PRADESH', 'MADHYA PRADESH1', 'MAHARASHTRA',
       'MANIPUR', 'MANIPUR1', 'MEGHALAYA', 'MIZORAM', 'NAGALAND',
       'NCT OF DELHI', 'ODISHA', 'PUDUCHERRY', 'PUDUCHERRY2', 'PUNJAB',
       'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TRIPURA', 'UTTAR PRADESH',
       'UTTAR PRADESH3', 'UTTARAKHAND', 'WEST BENGAL', 'WEST BENGAL1'],
      dtype=object)

In [ ]:
ap = economic_dataset[
    economic_dataset['state']=='ANDHRA PRADESH'
].copy()

ap['state']='TELANGANA'

economic_dataset = pd.concat(
    [economic_dataset, ap],
    ignore_index=True
)

In [ ]:
master_dataset = master_dataset.drop(
columns=[
'population_score',
'literacy_score',
'healthcare_score',
'crime_index',
'road_score',
'infrastructure_score',
'risk_score'
],
errors='ignore'
)

In [ ]:
master_dataset = master_dataset.merge(
    economic_dataset,
    on='state',
    how='left'
)

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3511
bathrooms               25186
balconies                9822
area_sqft               18955
property_age            13320
floor_number            19498
total_floor             13941
furnished_status        13320
price                       0
state                       0
population_score            0
literacy_score              0
healthcare_score            0
crime_index                 0
road_score                  0
infrastructure_score        0
risk_score                  0
dtype: int64

In [ ]:
# Save DataFrames as CSV files
all_df.to_csv('all_df.csv', index=False)
economic_dataset.to_csv('economic_dataset.csv', index=False)
master_dataset.to_csv('master_dataset.csv', index=False)

In [ ]:
from google.colab import files

files.download('all_df.csv')
files.download('economic_dataset.csv')
files.download('master_dataset.csv')

In [ ]:
print("blr:", blr['price'].isnull().sum())
print("gurgaon:", gurgaon['price'].isnull().sum())
print("hyd:", hyd['price'].isnull().sum())
print("kol:", kol['price'].isnull().sum())
print("mum:", mum['price'].isnull().sum())

blr: 0
gurgaon: 0
hyd: 0
kol: 0
mum: 0

In [ ]:
blr.shape
gurgaon.shape
hyd.shape
kol.shape
mum.shape

(9514, 16)

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3570
bathrooms               27871
balconies               10606
area_sqft               19547
property_age            13320
floor_number            19841
total_floor             13972
furnished_status        13320
price                   38502
state                       0
population_score            0
literacy_score              0
healthcare_score            0
crime_index                 0
road_score                  0
infrastructure_score        0
risk_score                  0
dtype: int64

In [ ]:
master_dataset['price'].isnull().sum()

np.int64(38502)

In [ ]:
print("blr:",blr['price'].isnull().sum())
print("gurgaon:",gurgaon['price'].isnull().sum())
print("hyd:",hyd['price'].isnull().sum())
print("kol:",kol['price'].isnull().sum())
print("mum:",mum['price'].isnull().sum())

blr: 0
gurgaon: 0
hyd: 0
kol: 0
mum: 0

In [ ]:
print(blr.shape)
print(gurgaon.shape)
print(hyd.shape)
print(kol.shape)
print(mum.shape)

(13320, 16)
(10704, 16)
(9487, 16)
(8797, 16)
(9514, 16)

In [ ]:
master_dataset[['price']].head()

    price
0   39.07
1  120.00
2   62.00
3   95.00
4   51.00

In [ ]:
master_dataset.dtypes

city                     object
locality                 object
property_type            object
bhk                     float64
bathrooms               float64
balconies               float64
area_sqft               float64
property_age            float64
floor_number             object
total_floor             float64
furnished_status        float64
price                   float64
state                    object
population_score        float64
literacy_score          float64
healthcare_score        float64
crime_index             float64
road_score              float64
infrastructure_score    float64
risk_score              float64
dtype: object

In [ ]:
master_dataset = master_dataset.T.drop_duplicates().T

In [ ]:
master_dataset.columns
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3570
bathrooms               27871
balconies               10606
area_sqft               19547
property_age            13320
floor_number            19841
total_floor             13972
furnished_status        13320
price                   38502
state                       0
population_score            0
literacy_score              0
healthcare_score            0
crime_index                 0
road_score                  0
infrastructure_score        0
risk_score                  0
dtype: int64

In [ ]:
property_master.columns[property_master.columns.duplicated()]

Index([], dtype='object')

In [ ]:
property_master['price'].head(20)

0     39.07
1     120.0
2      62.0
3      95.0
4      51.0
5      38.0
6     204.0
7     600.0
8     63.25
9     370.0
10     70.0
11    295.0
12     38.0
13     40.0
14    148.0
15     73.5
16     48.0
17     60.0
18    290.0
19     48.0
Name: price, dtype: object

In [ ]:
property_master['price'].dtype

dtype('O')

In [ ]:
property_master['price'].isnull().sum()

np.int64(0)

In [ ]:
print("blr :", blr['price'].isnull().sum())
print("gurgaon :", gurgaon['price'].isnull().sum())
print("hyd :", hyd['price'].isnull().sum())
print("kol :", kol['price'].isnull().sum())
print("mum :", mum['price'].isnull().sum())

blr : 0
gurgaon : 0
hyd : 0
kol : 0
mum : 0

In [ ]:
print("blr")
print(blr['price'].isnull().sum(), "/", len(blr))

print("gurgaon")
print(gurgaon['price'].isnull().sum(), "/", len(gurgaon))

print("hyd")
print(hyd['price'].isnull().sum(), "/", len(hyd))

print("kol")
print(kol['price'].isnull().sum(), "/", len(kol))

print("mum")
print(mum['price'].isnull().sum(), "/", len(mum))

blr
0 / 13320
gurgaon
0 / 10704
hyd
0 / 9487
kol
0 / 8797
mum
0 / 9514

In [ ]:
print(df2['PRICE'].head())
print(df3['PRICE'].head())
print(df4['PRICE'].head())
print(df5['PRICE'].head())

0    2.63 Cr
1     3.6 Cr
2     85,000
3    3.85 Cr
4     40,000
Name: PRICE, dtype: object
0             69.25 L
1      69.3  - 83.7 L
2    Price on Request
3     2.02  - 2.02 Cr
4     2.42  - 2.87 Cr
Name: PRICE, dtype: object
0           3.25 Cr
1            4.15 L
2    20,000/Bedroom
3         8,000/Bed
4         8,000/Bed
Name: PRICE, dtype: object
0     19.1 L Onwards
1    1.17  - 1.18 Cr
2    1.22  - 1.35 Cr
3      1.5  - 5.99 L
4         60  - 75 L
Name: PRICE, dtype: object

In [ ]:
master_dataset.isnull().sum()

city                        0
locality                    1
property_type               0
bhk                      3570
bathrooms               27871
balconies               10606
area_sqft               19547
property_age            13320
floor_number            19841
total_floor             13972
furnished_status        13320
price                   38502
state                       0
population_score            0
literacy_score              0
healthcare_score            0
crime_index                 0
road_score                  0
infrastructure_score        0
risk_score                  0
dtype: int64

In [ ]:
for name, df in [('blr', blr), ('gurgaon', gurgaon), ('hyd', hyd), ('kol', kol), ('mum', mum)]:
    print(name)
    print(df.columns[df.columns.duplicated()])

blr
Index([], dtype='object')
gurgaon
Index([], dtype='object')
hyd
Index([], dtype='object')
kol
Index([], dtype='object')
mum
Index([], dtype='object')

In [ ]:
print(blr.columns)
print(gurgaon.columns)
print(hyd.columns)
print(kol.columns)
print(mum.columns)

Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')
Index(['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies',
       'area_sqft', 'property_age', 'floor_number', 'total_floor',
       'furnished_status', 'parking', 'availability', 'latitude', 'longitude',
       'price'],
      dtype='object')

In [ ]:
all_df = pd.concat([blr, gurgaon, hyd, kol, mum], ignore_index=True)

In [ ]:
print(all_df.columns[all_df.columns.duplicated()])
print(all_df['price'].isnull().sum())

Index([], dtype='object')
0

In [ ]:
common_cols = set(blr.columns)
for df in [gurgaon, hyd, kol, mum]:
    common_cols &= set(df.columns)

print(len(common_cols))

for name, df in [('blr', blr), ('gurgaon', gurgaon), ('hyd', hyd), ('kol', kol), ('mum', mum)]:
    print(name, set(common_cols) - set(df.columns))

16
blr set()
gurgaon set()
hyd set()
kol set()
mum set()

In [ ]:
print(blr['price'].isnull().sum())
print(gurgaon['price'].isnull().sum())
print(hyd['price'].isnull().sum())
print(kol['price'].isnull().sum())
print(mum['price'].isnull().sum())

0
0
0
0
0

In [ ]:
all_df = pd.concat([blr, gurgaon, hyd, kol, mum], ignore_index=True)

print(all_df.shape)
print(all_df['price'].isnull().sum())

(51822, 16)
0

In [ ]:
age_df = pd.read_csv('AGE.csv')
furnish_df = pd.read_csv('FURNISH.csv')
ptype_df = pd.read_csv('PROPERTY_TYPE.csv')
floor_df = pd.read_csv('FLOOR_NUM.csv')
total_floor_df = pd.read_csv('TOTAL_FLOOR.csv')
amenities_df = pd.read_csv('AMENITIES.csv')

In [ ]:
print(age_df.columns)
print(furnish_df.columns)

Index(['id', 'label'], dtype='object')
Index(['id', 'label'], dtype='object')

In [ ]:
property_enriched = property_master.merge(
    age_df[['PROP_ID','AGE']],
    on='PROP_ID',
    how='left'
)

property_enriched = property_enriched.merge(
    furnish_df[['PROP_ID','FURNISH']],
    on='PROP_ID',
    how='left'
)

property_enriched = property_enriched.merge(
    ptype_df[['PROP_ID','PROPERTY_TYPE']],
    on='PROP_ID',
    how='left'
)

property_enriched = property_enriched.merge(
    floor_df[['PROP_ID','FLOOR_NUM']],
    on='PROP_ID',
    how='left'
)

property_enriched = property_enriched.merge(
    total_floor_df[['PROP_ID','TOTAL_FLOOR']],
    on='PROP_ID',
    how='left'
)

property_enriched = property_enriched.merge(
    amenities_df[['PROP_ID','AMENITIES']],
    on='PROP_ID',
    how='left'
)

KeyError: "None of [Index(['PROP_ID', 'AGE'], dtype='object')] are in the [columns]"

In [ ]:
print(age_df.columns.tolist())
print(furnish_df.columns.tolist())
print(ptype_df.columns.tolist())
print(floor_df.columns.tolist())
print(total_floor_df.columns.tolist())
print(amenities_df.columns.tolist())

['id', 'label']
['id', 'label']
['id', 'label']
['id', 'label']
['id', 'label']
['id', 'category', 'type', 'label']

In [ ]:
age_df.head()
furnish_df.head()
ptype_df.head()
floor_df.head()
total_floor_df.head()
amenities_df.head()

   id          category                  type                         label
0  25    Other Features  FEATURES_RESIDENTIAL                Waste Disposal
1  26    Other Features  FEATURES_RESIDENTIAL         Rain Water Harvesting
2  28    Other Features   FEATURES_COMMERCIAL        Bank Attached Property
3   2  Property Feature   FEATURES_COMMERCIAL                 Power Back-up
4   5  Property Feature  FEATURES_RESIDENTIAL  Feng Shui / Vaastu Compliant

In [ ]:
print(age_df.columns.tolist())
print(furnish_df.columns.tolist())
print(ptype_df.columns.tolist())
print(floor_df.columns.tolist())
print(total_floor_df.columns.tolist())
print(amenities_df.columns.tolist())

print(property_master.columns.tolist())

['id', 'label']
['id', 'label']
['id', 'label']
['id', 'label']
['id', 'label']
['id', 'category', 'type', 'label']
['city', 'locality', 'property_type', 'bhk', 'bathrooms', 'balconies', 'area_sqft', 'property_age', 'floor_number', 'total_floor', 'furnished_status', 'parking', 'availability', 'latitude', 'longitude', 'price', 'price']

In [ ]:
property_master = property_master.loc[:,~property_master.columns.duplicated()]

In [ ]:
property_master.shape

(51822, 16)

In [ ]:
property_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51822 entries, 0 to 51821
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   city              51822 non-null  object
 1   locality          51821 non-null  object
 2   property_type     51822 non-null  object
 3   bhk               48252 non-null  object
 4   bathrooms         23951 non-null  float64
 5   balconies         41216 non-null  float64
 6   area_sqft         51822 non-null  object
 7   property_age      38502 non-null  float64
 8   floor_number      31981 non-null  object
 9   total_floor       37850 non-null  float64
 10  furnished_status  38502 non-null  float64
 11  parking           0 non-null      float64
 12  availability      0 non-null      float64
 13  latitude          0 non-null      float64
 14  longitude         0 non-null      float64
 15  price             51822 non-null  object
dtypes: float64(9), object(7)
memory usage: 6.3+ MB

In [ ]:
property_master.describe()

,bathrooms,balconies,property_age,total_floor,furnished_status,parking,availability,latitude,longitude
count,23951.000000,41216.000000,38502.000000,37850.000000,38502.000000,0.0,0.0,0.0,0.0
mean,3.046345,1.835331,3.136097,14.942536,1.990286,NaN,NaN,NaN,NaN
std,1.476561,1.107071,2.182707,13.503293,1.601702,NaN,NaN,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
25%,2.000000,1.000000,1.000000,4.000000,0.000000,NaN,NaN,NaN,NaN
50%,3.000000,2.000000,3.000000,12.000000,2.000000,NaN,NaN,NaN,NaN
75%,4.000000,3.000000,5.000000,22.000000,4.000000,NaN,NaN,NaN,NaN
max,40.000000,4.000000,6.000000,117.000000,4.000000,NaN,NaN,NaN,NaN

In [ ]:
property_master.isnull().sum()

city                    0
locality                1
property_type           0
bhk                  3570
bathrooms           27871
balconies           10606
area_sqft               0
property_age        13320
floor_number        19841
total_floor         13972
furnished_status    13320
parking             51822
availability        51822
latitude            51822
longitude           51822
price                   0
dtype: int64

In [ ]:
missing_percent = (
    property_master.isnull().sum()
    /
    len(property_master)
)*100

missing_percent.sort_values(ascending=False)

availability        100.000000
latitude            100.000000
longitude           100.000000
parking             100.000000
bathrooms            53.782177
floor_number         38.286828
total_floor          26.961522
property_age         25.703369
furnished_status     25.703369
balconies            20.466211
bhk                   6.888966
locality              0.001930
area_sqft             0.000000
property_type         0.000000
city                  0.000000
price                 0.000000
dtype: float64

In [ ]:
property_master['area_sqft'].dtype

dtype('O')

In [ ]:
property_master['area_sqft'].unique()

array(['1056', '2600', '1440', ..., '1096-1373  sq.ft.',
       '713-911  sq.ft.', '627-903  sq.ft.'], dtype=object)

In [ ]:
property_master['bhk'] = (
    property_master['bhk']
    .astype(str)
    .str.extract('(\d+)')
)

property_master['bhk'] = property_master['bhk'].astype(float)

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_913/3819921544.py:4: SyntaxWarning: invalid escape sequence '\d'
  .str.extract('(\d+)')

In [ ]:
property_master['price'] = pd.to_numeric(
    property_master['price'],
    errors='coerce'
)

In [ ]:
property_master['price_per_sqft'] = (
    property_master['price']
    /
    property_master['area_sqft']
)

TypeError: unsupported operand type(s) for /: 'float' and 'str'

In [ ]:
floor_number / total_floor

NameError: name 'floor_number' is not defined

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving 01_District_wise_crimes_committed_IPC_2001_2012.csv to 01_District_wise_crimes_committed_IPC_2001_2012.csv
Saving 2011-IndiaStateDistSbDist-0000.xlsx to 2011-IndiaStateDistSbDist-0000.xlsx
Saving Anx3.36.csv to Anx3.36.csv
Saving DDW_PCA0000_2011_Indiastatedist.xlsx to DDW_PCA0000_2011_Indiastatedist.xlsx
Saving No_Of_Sub_Div_Hosp_District_Hosp_Mobile_Medical_Units_Functioning_1.csv to No_Of_Sub_Div_Hosp_District_Hosp_Mobile_Medical_Units_Functioning_1.csv
Saving RS_249_AU3914.csv to RS_249_AU3914.csv
Saving rural_water_supply_performance_2009.csv to rural_water_supply_performance_2009.csv
Saving Table_No_7.2_States-UTs-2013.csv to Table_No_7.2_States-UTs-2013.csv
Saving Table29.1.xls to Table29.1.xls
Saving urban_water_supply_performance_2009.csv to urban_water_supply_performance_2009.csv

In [ ]:
crime_df= pd.read_csv("01_District_wise_crimes_committed_IPC_2001_2012.csv")
population_df= pd.read_excel("2011-IndiaStateDistSbDist-0000.xlsx")
demographics_df= pd.read_excel("Table29.1.xls")
roads_df = pd.read_csv("Table_No_7.2_States-UTs-2013.csv")
railways_df = pd.read_csv("RS_249_AU3914.csv")
airports_df = pd.read_excel("DDW_PCA0000_2011_Indiastatedist.xlsx")
urban_water_df = pd.read_csv("urban_water_supply_performance_2009.csv")
rural_water_df = pd.read_csv("rural_water_supply_performance_2009.csv")
hospitals_df = pd.read_csv("No_Of_Sub_Div_Hosp_District_Hosp_Mobile_Medical_Units_Functioning_1.csv")

In [ ]:
print(crime_df.columns)
print(population_df.columns)
print(demographics_df.columns)
print(roads_df.columns)
print(railways_df.columns)
print(airports_df.columns)
print(urban_water_df.columns)
print(rural_water_df.columns)
print(hospitals_df.columns)

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')
Index(['State', 'District', 'Subdistt', 'Town/Village', 'Ward', 'EB', 'Level',
       'Name', 'TRU', 'No_HH', 'TOT_P', 'TOT_M', 'TOT_F', 'P_06', 'M_06',
       'F_06', 'P_SC', 'M_SC', 'F_SC', 'P_ST', 'M_ST', 'F_ST', 'P_LIT',
       'M_LIT', 'F_LIT', 'P_ILL', 'M_ILL', 'F_ILL', 'TOT_WORK_P', 'TOT_WORK_M',
       'TOT_WORK_F', 'MAINWORK_P', 'MAINWORK_M', 'MAINWORK_F', 'MAIN_CL_P',
       'MAIN_CL_M', 'MAIN_CL_F', 'MAIN_AL_P', 'MAIN_AL_M', 'MAIN_AL_F',
       'MAIN_HH_P', 'MAIN_HH_M', 'MAIN_HH_F', 'MAIN_OT_P', 'MAIN_OT_M',
       'MAIN_OT_F', 'MARGWORK_P', 'MARGWORK_M', 'MARGWORK_F', 'MARG_CL_P',
       'MARG_CL_M', 'MARG_CL_F', 'MARG_AL_P', 'MARG_AL_M', 'MARG_AL_F',
       'MARG_HH_P', 'MARG_HH_M', 'MARG_HH_F', 'MARG_OT_P', 'MARG_OT_M',
       'MARG_OT_F', 'MARGWORK_3_6_P', 'MARGWORK_3_6_M', 'MARGWORK_3_6_F',
       'MARG_CL_3_6_P', 'MARG_CL_3_6_M', 'MARG_CL_3_6_F', 'MARG_AL_3_6_P',
       'MARG_AL_3_6_M', 'MARG_AL_3_6_F', 'MARG_HH_3_6_P', 'MARG_HH_3_6_M',
       'MARG_HH_3_6_F', 'MARG_OT_3_6_P', 'MARG_OT_3_6_M', 'MARG_OT_3_6_F',
       'MARGWORK_0_3_P', 'MARGWORK_0_3_M', 'MARGWORK_0_3_F', 'MARG_CL_0_3_P',
       'MARG_CL_0_3_M', 'MARG_CL_0_3_F', 'MARG_AL_0_3_P', 'MARG_AL_0_3_M',
       'MARG_AL_0_3_F', 'MARG_HH_0_3_P', 'MARG_HH_0_3_M', 'MARG_HH_0_3_F',
       'MARG_OT_0_3_P', 'MARG_OT_0_3_M', 'MARG_OT_0_3_F', 'NON_WORK_P',
       'NON_WORK_M', 'NON_WORK_F'],
      dtype='object')
Index(['  Year', 'Number of institutions - University/Colleges(*)',
       'Number of institutions - Schools(#)', 'Number of institutions - Total',
       'Number of scholars (in millions) - University/Colleges - Total',
       'Number of scholars (in millions) - University/Colleges - Women',
       'Number of scholars (in millions) - Schools(@) - Total',
       'Number of scholars (in millions) - Schools(@) - Women',
       'Number of scholars (in millions) - Total for Colleges and Schools - Total',
       'Number of scholars (in millions) - Total for Colleges and Schools - Women',
       'GDP at Current Prices (at factor cost)-(in Crore)',
       'Total Public Expenditure by all Sectors-(in Crore)',
       'Expenditure on Education by Education & Other Deptts.-(in Crore)',
       'Expenditure on Education by Education & Other Deptts. as %age of Public Expenditure',
       'Expenditure on Education by Education & Other Deptts as %ageof GDP'],
      dtype='object')
Index(['Category', 'States/UTs', 'Total (A+B)', 'Surfaced - Total (A)',
       'Surfaced - W.B.M.', 'Surfaced - B.T./C.C', 'Unsurfaced - Total (B)'],
      dtype='object')
Index(['Zonal Railway', 'Railway Land'], dtype='object')
Index(['State', 'District', 'Subdistt', 'Town/Village', 'Ward', 'EB', 'Level',
       'Name', 'TRU', 'No_HH', 'TOT_P', 'TOT_M', 'TOT_F', 'P_06', 'M_06',
       'F_06', 'P_SC', 'M_SC', 'F_SC', 'P_ST', 'M_ST', 'F_ST', 'P_LIT',
       'M_LIT', 'F_LIT', 'P_ILL', 'M_ILL', 'F_ILL', 'TOT_WORK_P', 'TOT_WORK_M',
       'TOT_WORK_F', 'MAINWORK_P', 'MAINWORK_M', 'MAINWORK_F', 'MAIN_CL_P',
       'MAIN_CL_M', 'MAIN_CL_F', 'MAIN_AL_P', 'MAIN_AL_M', 'MAIN_AL_F',
       'MAIN_HH_P', 'MAIN_HH_M', 'MAIN_HH_F', 'MAIN_OT_P', 'MAIN_OT_M',
       'MAIN_OT_F', 'MARGWORK_P', 'MARGWORK_M', 'MARGWORK_F', 'MARG_CL_P',
       'MARG_CL_M', 'MARG_CL_F', 'MARG_AL_P', 'MARG_AL_M', 'MARG_AL_F',
       'MARG_HH_P', 'MARG_HH_M', 'MARG_HH_F', 'MARG_OT_P', 'MARG_OT_M',
       'MARG_OT_F', 'MARGWORK_3_6_P', 'MARGWORK_3_6_M', 'MARGWORK_3_6_F',
       'MARG_CL_3_6_P', 'MARG_CL_3_6_M', 'MARG_CL_3_6_F', 'MARG_AL_3_6_P',
       'MARG_AL_3_6_M', 'MARG_AL_3_6_F', 'MARG_HH_3_6_P', 'MARG_HH_3_6_M',
       'MARG_HH_3_6_F', 'MARG_OT_3_6_P', 'MARG_OT_3_6_M', 'MARG_OT_3_6_F',
       'MARGWORK_0_3_P', 'MARGWORK_0_3_M', 'MARGWORK_0_3_F', 'MARG_CL_0_3_P',
       'MARG_CL_0_3_M', 'MARG_CL_0_3_F', 'MARG_AL_0_3_P', 'MARG_AL_0_3_M',
       'MARG_AL_0_3_F', 'MARG_HH_0_3_P', 'MARG_HH_0_3_M', 'MARG_HH_0_3_F',
       'MARG_OT_0_3_P', 'MARG_OT_0_3_M', 'MARG_OT_0_3_F', 'NON_WORK_P',
       'NON_WORK_M', 'NON_WORK_F'],
      dtype='object')
Index(['Sl.No', 'Year', 'No. of Urban Schemes Completed',
       'Expenditure ( Rs.in Crores)'],
      dtype='object')
Index(['Sl.No', 'Year', 'Habitations Benefitted',
       'Expenditure ( Rs. in Lakhs)'],
      dtype='object')
Index(['S. No.', 'State/UT', 'Sub Divisional Hospital (SDH)',
       'District Hospital (DH)', 'Mobile Medical Units (MMU)'],
      dtype='object')

In [ ]:
crime_state = crime.groupby('STATE/UT')['TOTAL IPC CRIMES'].sum().reset_index()

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler((0,10))

crime_state['crime_index'] = scaler.fit_transform(
    crime_state[['TOTAL IPC CRIMES']]
)

In [ ]:
crime_state = crime_state[['STATE/UT','crime_index']]

In [ ]:
population['Level'].value_counts()

Level
SUB-DISTRICT    17964
DISTRICT         1920
STATE             105
India               3
Name: count, dtype: int64

In [ ]:
state_pop = population[
    population['Level'] == 'STATE'
].copy()

In [ ]:
print(state_pop.shape)

(105, 94)

In [ ]:
print(population['Level'].unique())

print(population['Level'].value_counts())

population[['Level','Name','TOT_P']].head(20)

['India' 'STATE' 'DISTRICT' 'SUB-DISTRICT']
Level
SUB-DISTRICT    17964
DISTRICT         1920
STATE             105
India               3
Name: count, dtype: int64

           Level             Name       TOT_P
0          India            India  1210854977
1          India            India   833748852
2          India            India   377106125
3          STATE  JAMMU & KASHMIR    12541302
4          STATE  JAMMU & KASHMIR     9108060
5          STATE  JAMMU & KASHMIR     3433242
6       DISTRICT          Kupwara      870354
7       DISTRICT          Kupwara      765625
8       DISTRICT          Kupwara      104729
9   SUB-DISTRICT          Kupwara      540914
10  SUB-DISTRICT          Kupwara      465323
11  SUB-DISTRICT          Kupwara       75591
12  SUB-DISTRICT         Handwara      269311
13  SUB-DISTRICT         Handwara      255711
14  SUB-DISTRICT         Handwara       13600
15  SUB-DISTRICT           Karnah       60129
16  SUB-DISTRICT           Karnah       44591
17  SUB-DISTRICT           Karnah       15538
18      DISTRICT           Badgam      753745
19      DISTRICT           Badgam      655833

In [ ]:
state_pop = state_pop.groupby('Name').first().reset_index()

In [ ]:
state_pop[['Name','TOT_P']].head()

                        Name      TOT_P
0  ANDAMAN & NICOBAR ISLANDS     380581
1             ANDHRA PRADESH   84580777
2          ARUNACHAL PRADESH    1383727
3                      ASSAM   31205576
4                      BIHAR  104099452

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,10))

state_pop['population_score'] = scaler.fit_transform(
    state_pop[['TOT_P']]
)

In [ ]:
state_pop['literacy_rate'] = (
    state_pop['P_LIT']
    /
    state_pop['TOT_P']
)*100

In [ ]:
state_pop['literacy_score'] = scaler.fit_transform(
    state_pop[['literacy_rate']]
)

In [ ]:
state_pop = state_pop[
    [
        'Name',
        'population_score',
        'literacy_score'
    ]
]

In [ ]:
state_pop.rename(
    columns={'Name':'state'},
    inplace=True
)

In [ ]:
state_pop.head()

                       state  population_score  literacy_score
0  ANDAMAN & NICOBAR ISLANDS          0.015825        7.957910
1             ANDHRA PRADESH          4.231149        2.763337
2          ARUNACHAL PRADESH          0.066046        1.456541
3                      ASSAM          1.559021        3.261622
4                      BIHAR          5.208315        0.000000

In [ ]:
roads['road_score']=scaler.fit_transform(
roads[['Total (A+B)']]
)

In [ ]:
roads=roads[['States/UTs','road_score']]

In [ ]:
railways['transport_score']=scaler.fit_transform(
railways[['Railway Land']]
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler((0,10))

urban_water['urban_score'] = scaler.fit_transform(
    urban_water[['No. of Urban Schemes Completed']]
)

In [ ]:
rural_water['rural_score'] = scaler.fit_transform(
    rural_water[['Habitations Benefitted']]
)

In [ ]:
urban_score = urban_water['urban_score'].mean()

rural_score = rural_water['rural_score'].mean()

In [ ]:
water_score = ( 0.7*urban_score + 0.3*rural_score
)

In [ ]:
print(hospitals.columns)

display(hospitals.head())

Index(['S. No.', 'State/UT', 'Sub Divisional Hospital (SDH)',
       'District Hospital (DH)', 'Mobile Medical Units (MMU)'],
      dtype='object')

,S. No.,State/UT,Sub Divisional Hospital (SDH),District Hospital (DH),Mobile Medical Units (MMU)
0,1,Andhra Pradesh1,58.0,17,475
1,2,Arunachal Pradesh,0.0,14,16
2,3,Assam,13.0,24,27
3,4,Bihar,40.0,36,48
4,5,Chhattisgarh,17.0,17,0

In [ ]:
hospitals.isnull().sum()

S. No.                           0
State/UT                         0
Sub Divisional Hospital (SDH)    3
District Hospital (DH)           0
Mobile Medical Units (MMU)       0
dtype: int64

In [ ]:
print(hospitals.dtypes)

S. No.                             int64
State/UT                          object
Sub Divisional Hospital (SDH)    float64
District Hospital (DH)             int64
Mobile Medical Units (MMU)        object
dtype: object

In [ ]:
display(hospitals.head(10))

,S. No.,State/UT,Sub Divisional Hospital (SDH),District Hospital (DH),Mobile Medical Units (MMU)
0,1,Andhra Pradesh1,58.0,17,475
1,2,Arunachal Pradesh,0.0,14,16
2,3,Assam,13.0,24,27
3,4,Bihar,40.0,36,48
4,5,Chhattisgarh,17.0,17,0
5,6,Goa,0.0,2,4
6,7,Gujarat,26.0,24,88
7,8,Haryana,25.0,21,6
8,9,Himachal Pradesh,36.0,12,1
9,10,Jammu & Kashmir+,0.0,22,13

In [ ]:
cols = [
    'Sub Divisional Hospital (SDH)',
    'District Hospital (DH)',
    'Mobile Medical Units (MMU)'
]

for col in cols:
    hospitals[col] = pd.to_numeric(
        hospitals[col],
        errors='coerce'
    )

In [ ]:
hospitals[cols] = hospitals[cols].fillna(0)

In [ ]:
hospitals['healthcare_capacity'] = (hospitals['Sub Divisional Hospital (SDH)'] + hospitals['District Hospital (DH)'] + hospitals['Mobile Medical Units (MMU)']
)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler((0,10))

hospitals['healthcare_score'] = scaler.fit_transform(
    hospitals[['healthcare_capacity']]
)

In [ ]:
healthcare = hospitals[
    ['State/UT','healthcare_score']
].copy()

In [ ]:
healthcare.rename(
    columns={'State/UT':'state'},
    inplace=True
)

In [ ]:
healthcare.head()

               state  healthcare_score
0    Andhra Pradesh1          3.433584
1  Arunachal Pradesh          0.175439
2              Assam          0.388471
3              Bihar          0.764411
4       Chhattisgarh          0.200501

In [ ]:
state_pop = population[
    population['Level'] == 'STATE'
].copy()

In [ ]:
state_pop = state_pop.groupby('Name').first().reset_index()

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler((0,10))

state_pop['population_score'] = scaler.fit_transform(
    state_pop[['TOT_P']]
)

state_pop['literacy_rate'] = (
    state_pop['P_LIT'] /
    state_pop['TOT_P']
) * 100

state_pop['literacy_score'] = scaler.fit_transform(
    state_pop[['literacy_rate']]
)

In [ ]:
population_df = state_pop[
    ['Name', 'population_score', 'literacy_score']
].copy()

population_df.rename(
    columns={'Name':'state'},
    inplace=True
)

In [ ]:
crime_state.rename(
    columns={'STATE/UT':'state'},
    inplace=True
)

In [ ]:
roads.rename(
    columns={'States/UTs':'state'},
    inplace=True
)

In [ ]:
population_df['state'] = population_df['state'].str.upper().str.strip()
healthcare['state'] = healthcare['state'].str.upper().str.strip()
crime_state['state'] = crime_state['state'].str.upper().str.strip()
roads['state'] = roads['state'].str.upper().str.strip()

In [ ]:
print(population_df.columns)
print(healthcare.columns)
print(crime_state.columns)
print(roads.columns)

Index(['state', 'population_score', 'literacy_score'], dtype='object')
Index(['state', 'healthcare_score'], dtype='object')
Index(['state', 'crime_index'], dtype='object')
Index(['state', 'road_score'], dtype='object')

In [ ]:
economic_dataset = population_df.merge(
    healthcare,
    on='state',
    how='outer'
)

In [ ]:
economic_dataset.head()

,state,population_score,literacy_score,healthcare_score
0,ALL INDIA TOTAL,NaN,NaN,10.000000
1,ANDAMAN & NICOBAR ISLANDS,0.015825,7.957910,0.006266
2,ANDHRA PRADESH,4.231149,2.763337,NaN
3,ANDHRA PRADESH1,NaN,NaN,3.433584
4,ARUNACHAL PRADESH,0.066046,1.456541,0.175439

In [ ]:
economic_dataset = economic_dataset.merge(
    crime_state,
    on='state',
    how='outer'
)

In [ ]:
economic_dataset = economic_dataset.merge(
    roads,
    on='state',
    how='outer'
)

In [ ]:
economic_dataset.fillna(
    economic_dataset.mean(numeric_only=True),
    inplace=True
)

In [ ]:
economic_dataset['infrastructure_score'] = (
      0.35*economic_dataset['road_score']
    + 0.35*economic_dataset['healthcare_score']
    + 0.15*economic_dataset['population_score']
    + 0.15*economic_dataset['literacy_score']
)

In [ ]:
economic_dataset['risk_score'] = (
      0.7*economic_dataset['crime_index']
    + 0.3*(10-economic_dataset['infrastructure_score'])
)

In [ ]:
economic_dataset.head()

,state,population_score,literacy_score,healthcare_score,crime_index,road_score,infrastructure_score,risk_score
0,A & N ISLANDS,1.728749,5.126189,0.861355,0.034641,0.644127,1.555159,2.557701
1,ALL INDIA,1.728749,5.126189,0.861355,2.831612,10.000000,4.829715,3.533214
2,ALL INDIA TOTAL,1.728749,5.126189,10.000000,2.831612,0.644127,4.753685,3.556023
3,ANDAMAN & NICOBAR ISLANDS,0.015825,7.957910,0.006266,2.831612,0.003152,1.199357,4.622322
4,ANDHRA PRADESH,4.231149,2.763337,0.861355,8.363926,0.243972,1.436037,8.423937

In [ ]:
economic_dataset.to_csv(
    "economic_dataset.csv",
    index=False
)

In [ ]:
city_to_state = {
    'BENGALURU':'KARNATAKA',
    'BANGALORE':'KARNATAKA',
    'HYDERABAD':'TELANGANA',
    'MUMBAI':'MAHARASHTRA',
    'KOLKATA':'WEST BENGAL',
    'GURGAON':'HARYANA'
}

In [ ]:
property_master['city'] = (
    property_master['city']
    .str.upper()
    .str.strip()
)

In [ ]:
property_master['state'] = (
    property_master['city']
    .map(city_to_state)
)

In [ ]:
property_master[['city','state']].head()

        city      state
0  BANGALORE  KARNATAKA
1  BANGALORE  KARNATAKA
2  BANGALORE  KARNATAKA
3  BANGALORE  KARNATAKA
4  BANGALORE  KARNATAKA

In [ ]:
property_master['state'] = (
    property_master['state']
    .str.upper()
    .str.strip()
)

economic_dataset['state'] = (
    economic_dataset['state']
    .str.upper()
    .str.strip()
)

In [ ]:
master_dataset = property_master.merge(
    economic_dataset,
    on='state',
    how='left'
)

In [ ]:
master_dataset.shape

(51822, 24)

In [ ]:
master_dataset.head()

,city,locality,property_type,bhk,bathrooms,balconies,area_sqft,property_age,floor_number,total_floor,...,longitude,price,state,population_score,literacy_score,healthcare_score,crime_index,road_score,infrastructure_score,risk_score
0,BANGALORE,Electronic City Phase II,Super built-up Area,2.0,2.0,1.0,1056,NaN,NaN,NaN,...,NaN,39.07,KARNATAKA,3.055393,4.763429,0.861355,6.134701,0.748506,1.736275,6.773409
1,BANGALORE,Chikka Tirupathi,Plot Area,4.0,5.0,3.0,2600,NaN,NaN,NaN,...,NaN,120.00,KARNATAKA,3.055393,4.763429,0.861355,6.134701,0.748506,1.736275,6.773409
2,BANGALORE,Uttarahalli,Built-up Area,3.0,2.0,3.0,1440,NaN,NaN,NaN,...,NaN,62.00,KARNATAKA,3.055393,4.763429,0.861355,6.134701,0.748506,1.736275,6.773409
3,BANGALORE,Lingadheeranahalli,Super built-up Area,3.0,3.0,1.0,1521,NaN,NaN,NaN,...,NaN,95.00,KARNATAKA,3.055393,4.763429,0.861355,6.134701,0.748506,1.736275,6.773409
4,BANGALORE,Kothanur,Super built-up Area,2.0,2.0,1.0,1200,NaN,NaN,NaN,...,NaN,51.00,KARNATAKA,3.055393,4.763429,0.861355,6.134701,0.748506,1.736275,6.773409

In [ ]:
master_dataset.to_csv(
    "master_dataset.csv",
    index=False
)